import type { Metadata } from 'next'

import '@style/index.scss'
import '@style/theme.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { defaultColor } from '@lib/colors'

import Topbar from '@components/Topbar'
import Sidebar from '@components/Sidebar'
import ColorMenu from '@components/ColorMenu'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' data-color-theme={defaultColor}>
      <head>
        <link id='themed-icon' rel='icon' />
      </head>
      <body className='w-full h-screen overflow-y-hidden'>
        <Sidebar />
        <ColorMenu />
        <div id='scrollArea' className='flex flex-col overflow-y-auto w-full h-full'>
          <Topbar />
          <main className='w-full grow z-content'>{children}</main>
        </div>
      </body>
    </html>
  )
}
