name: Enforce code style

on: [workflow_call, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix package manager
        uses: nixbuild/nix-quick-install-action@v27
      - name: Fetch cached nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/package-lock.json') }}
          restore-prefixes-first-match: nix-${{ runner.os }}
      - name: Run linter
        run: nix run .#lint
